# Streamlit Configuration File

# Theme Settings
[theme]
# Choose between 'light' or 'dark' for the theme.
base="dark"
# Optionally set the primary color for the app (e.g., 'blue', 'green', 'red')
primaryColor = "green"
# Accent color for widgets and buttons (a nice contrast color)
secondaryBackgroundColor = "#333333"
# Background color for your app's main container
backgroundColor = "#202020"
# Font settings (use any of the Google fonts: 'serif', 'sans-serif', 'monospace', 'Roboto', etc.)
font = "Roboto"
# Choose font for the header
headerFont = "sans-serif"
# Choose font for the body content
bodyFont = "Roboto"
# Set the title color (e.g., white, grey)
titleColor = "#F0F0F0"

# Layout Settings
[layout]
# Maximum width of the app (e.g., '1200px', '100%', etc.)
maxWidth = "1200px"
# Spacing for main content
padding = "20px"

# App Header Settings
[app]
# Set your app header logo (use the full path or relative path)
# headerLogo = "path/to/logo.png"
# Hide the menu bar on the top right (set to true to hide it)
menu = false

# Configure the footer
[footer]
# You can display a custom footer text or message
footerText = "Developed with ❤️ by Prasad Upasani"
# To display the footer, set to true
displayFooter = true

# Run options
[server]
# The server can be set to always run on a specific port (e.g., 8501)
headless = true
port = 8501
enableCORS = false
